[tool.poetry]
name = "workflow"
version = "0.0.1"
description = ""
authors = ["Omkar Pawar <omkarpawar13797@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
